good_eats/config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

     resources :restaurants do
       resources :reviews
     end

end

good_eats/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  validates :name,
    presence: true

end

good_eats/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :rating,
    presence: true

  validates :body,
    presence: true
    
end

good_eats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

good_eats/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/10
  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = Review.where(restaurant_id: @restaurant[:id])
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end

  # GET /restaurants/search
  # def search
  #   @restaurant = Restaurant.search(params[:query])
  # end

  # GET /restaurants/1/edit
  # def edit
  #   @restaurant = Restaurant.find(params[:id])
  # end

  # PATCH /restaurants/1/update
  # def update
  #   @restaurant = Restaurant.find(params[:id])
  #
  #   if @restaurant.update(restaurant_params)
  #     redirect_to @restaurant
  #   else
  #     @restaurant.edit
  #   end
  # end

  # DELETE /restaurants/id/delete
  # def destroy
  #   Restaurant.destroy(params[:id])
  #   redirect_to :action => "index"
  # end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zipcode, :description, :category)
  end
end

good_eats/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def index
end

def new
  @review = Review.new
  @restaurant = Restaurant.find(params[:restaurant_id])
end

def show
  @review = Review.find(params[:restaurant_id])
end


def create
  @review = Review.new(review_params)
  @restaurant = Restaurant.find(params[:restaurant_id])
  @review.restaurant_id = params[:restaurant_id]
  @review.save

  redirect_to restaurants_path
end

private
def review_params
  params.require(:review).permit(:body)
end

end

good_eats/app/helpers/application_helper.rb
module ApplicationHelper
end

good_eats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

good_eats/app/views/restaurants/index.html.erb
<%= link_to "New", new_restaurant_path %>


<% @restaurants.each do |restaurant| %>
  <li><%= link_to "#{restaurant.name}", restaurant_path(restaurant) %></li>
<% end %>

good_eats/app/views/restaurants/new.html.erb
<%= link_to "Home", restaurants_path %>


<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zipcode %>
  <%= f.text_field :zipcode %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.submit "Submit"%>
<% end %>

good_eats/app/views/restaurants/show.html.erb
<%= link_to "Home", restaurants_path %>

<ul>

  <li><%= @restaurant.name %></li>
  <li><%= @restaurant.address %></li>
  <li><%= @restaurant.city %></li>
  <li><%= @restaurant.state %></li>
  <li><%= @restaurant.zipcode %></li>
  <li><%= @restaurant.description %></li>
  <li><%= @restaurant.category %></li>
</ul>

<%= link_to "Review this", new_restaurant_review_path(params[:id]) %>


<% @reviews.each do |review|%>
  <li><%= review.rating %></li>
  <li><%= review.body %></li>
<% end %>

good_eats/app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :rating %>
  <%= f.select :rating, %w(1 2 3 4 5) %><hr><br>
  <%= f.label :body, "Add an Review:" %><br>
  <%= f.text_area :body %>
  <%= f.submit :class => "button" %>
<% end %>